import type { SearchQualityCase } from "./types";

export const SEARCH_QUALITY_DATASET: readonly SearchQualityCase[] = [
  { query: "cute", kind: "exact", expected_slugs: [], min_results: 5 },
  { query: "love", kind: "exact", expected_slugs: [], min_results: 5 },
  { query: "kawaii", kind: "exact", expected_slugs: [], min_results: 3 },
  { query: "happy", kind: "exact", expected_slugs: [], min_results: 5 },
  { query: "sad", kind: "exact", expected_slugs: [], min_results: 5 },
  { query: "angry", kind: "exact", expected_slugs: [], min_results: 3 },
  { query: "crying", kind: "partial", expected_slugs: [], min_results: 3 },
  { query: "laughing", kind: "partial", expected_slugs: [], min_results: 3 },
  { query: "cat", kind: "exact", expected_slugs: [], min_results: 3 },
  { query: "dog", kind: "exact", expected_slugs: [], min_results: 2 },
  { query: "hug", kind: "exact", expected_slugs: [], min_results: 2 },
  { query: "kiss", kind: "exact", expected_slugs: [], min_results: 2 },
  { query: "sorry", kind: "exact", expected_slugs: [], min_results: 2 },
  { query: "thank you", kind: "natural", expected_slugs: [], min_results: 2 },
  { query: "friendship", kind: "natural", expected_slugs: [], min_results: 2 },
  { query: "anime", kind: "category", expected_slugs: [], min_results: 3 },
  { query: "aesthetic", kind: "category", expected_slugs: [], min_results: 2 },
  { query: "funny", kind: "exact", expected_slugs: [], min_results: 3 },
  { query: "shy", kind: "exact", expected_slugs: [], min_results: 2 },
  { query: "blush", kind: "misspelling", expected_slugs: [], min_results: 2 },
  { query: "cute kaomoji", kind: "natural", expected_slugs: [], min_results: 5 },
  { query: "love kaomoji", kind: "natural", expected_slugs: [], min_results: 5 },
  { query: "kaomoji for girlfriend", kind: "natural", expected_slugs: [], min_results: 2 },
  { query: "kaomoji for boyfriend", kind: "natural", expected_slugs: [], min_results: 2 },
  { query: "happy kaomoji", kind: "natural", expected_slugs: [], min_results: 5 },
  { query: "sad face", kind: "natural", expected_slugs: [], min_results: 3 },
  { query: "angry face", kind: "natural", expected_slugs: [], min_results: 2 },
  { query: "cute cat", kind: "natural", expected_slugs: [], min_results: 2 },
  { query: "instagram", kind: "category", expected_slugs: [], min_results: 1 },
  { query: "discord", kind: "category", expected_slugs: [], min_results: 1 },
  { query: "whatsapp", kind: "category", expected_slugs: [], min_results: 1 },
  { query: "(｡♥‿♥｡)", kind: "character", expected_slugs: [], min_results: 1 },
];
