import type { SourceRecord } from "../types";

export type Phase5SourceStatus =
  | "ACTIVE_RELEVANT"
  | "ACTIVE_PARTIALLY_RELEVANT"
  | "SOURCE_MISMATCH"
  | "INACCESSIBLE"
  | "NO_RELEVANT_CONTENT"
  | "REVIEW_REQUIRED"
  | "NOT_PERMITTED";

export interface Phase5SourceDefinition extends SourceRecord {
  readonly repository_url: string | null;
  readonly source_type: "github" | "website" | "wikimedia" | "huggingface" | "npm" | "unknown";
  readonly phase5_status: Phase5SourceStatus;
}

function gh(owner: string, repo: string): Pick<Phase5SourceDefinition, "repository_url" | "source_type"> {
  return {
    repository_url: `https://github.com/${owner}/${repo}`,
    source_type: "github",
  };
}

/** Phase 5: 21 unique source identities (23 candidates minus ToolCalculator duplicate). */
export const PHASE5_SOURCE_REGISTRY: readonly Phase5SourceDefinition[] = [
  {
    source_id: "emoticon-data",
    source_name: "emoticon-data (w33ble)",
    source_url: "https://github.com/w33ble/emoticon-data",
    repository_url: "https://github.com/w33ble/emoticon-data",
    source_type: "github",
    data_type: "emoticon",
    collection_method: "github_raw",
    license_status: "APPROVED",
    license_name: "MIT",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://github.com/w33ble/emoticon-data/blob/master/LICENSE",
    license_url: "https://github.com/w33ble/emoticon-data/blob/master/LICENSE",
    verification_date: "2026-08-19",
    verification_status: "VERIFIED",
    quality_status: "HIGH",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: true,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "kaomoji-tagged",
    source_name: "kaomoji-data (kaomojikan)",
    source_url: "https://github.com/kaomojikan/kaomoji-data",
    repository_url: "https://github.com/kaomojikan/kaomoji-data",
    source_type: "github",
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "APPROVED",
    license_name: "MIT",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://github.com/kaomojikan/kaomoji-data/blob/main/LICENSE",
    license_url: "https://github.com/kaomojikan/kaomoji-data/blob/main/LICENSE",
    verification_date: "2026-08-19",
    verification_status: "VERIFIED",
    quality_status: "HIGH",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: true,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "wikipedia",
    source_name: "Wikipedia",
    source_url: "https://en.wikipedia.org/wiki/List_of_emoticons",
    repository_url: null,
    source_type: "wikimedia",
    data_type: "mixed",
    collection_method: "wikimedia_api",
    license_status: "ATTRIBUTION_REQUIRED",
    license_name: "CC BY-SA 3.0",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0/",
    verification_date: "2026-08-19",
    verification_status: "PARTIALLY_VERIFIED",
    quality_status: "MEDIUM",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: true,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "toolcalculator",
    source_name: "ToolCalculator",
    source_url: "https://www.toolcalculator.com",
    repository_url: null,
    source_type: "website",
    data_type: "emoticon",
    collection_method: "discovery_only",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: ["Single source_id — duplicate list entry resolved"],
    enabled_for_collection: false,
    enabled_for_publication: false,
    phase5_status: "SOURCE_MISMATCH",
  },
  {
    source_id: "kaomojis-org",
    source_name: "kaomojis.org",
    source_url: "https://kaomojis.org",
    repository_url: null,
    source_type: "website",
    data_type: "kaomoji",
    collection_method: "discovery_only",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [],
    enabled_for_collection: false,
    enabled_for_publication: false,
    phase5_status: "SOURCE_MISMATCH",
  },
  {
    source_id: "messletters",
    source_name: "Messletters",
    source_url: "https://www.messletters.com/en/emoticons/",
    repository_url: null,
    source_type: "website",
    data_type: "emoticon",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "textemoticons",
    source_name: "TextEmoticons",
    source_url: "https://textemoticons.com",
    repository_url: null,
    source_type: "website",
    data_type: "emoticon",
    collection_method: "discovery_only",
    license_status: "UNKNOWN",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [],
    enabled_for_collection: false,
    enabled_for_publication: false,
    phase5_status: "INACCESSIBLE",
  },
  {
    source_id: "emoticonstext",
    source_name: "EmoticonsText",
    source_url: "https://www.emoticonstext.com",
    repository_url: null,
    source_type: "website",
    data_type: "emoticon",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "slangit",
    source_name: "SlangIt",
    source_url: "https://slangit.com/emoticons",
    repository_url: null,
    source_type: "website",
    data_type: "emoticon",
    collection_method: "discovery_only",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: "https://slangit.com/terms.php",
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [],
    enabled_for_collection: false,
    enabled_for_publication: false,
    phase5_status: "INACCESSIBLE",
  },
  {
    source_id: "fastemoji",
    source_name: "FastEmoji",
    source_url: "https://www.fastemoji.com",
    repository_url: null,
    source_type: "website",
    data_type: "mixed",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "UNVERIFIED",
    quality_status: "LOW",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "ACTIVE_PARTIALLY_RELEVANT",
  },
  {
    source_id: "kaomoji-collection",
    source_name: "kaomoji-collection",
    source_url: "https://github.com/kaomojiya-collection/kaomoji-collection",
    ...gh("kaomojiya-collection", "kaomoji-collection"),
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "APPROVED",
    license_name: "MIT",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://github.com/kaomojiya-collection/kaomoji-collection/blob/main/LICENSE",
    license_url: "https://github.com/kaomojiya-collection/kaomoji-collection/blob/main/LICENSE",
    verification_date: "2026-08-19",
    verification_status: "VERIFIED",
    quality_status: "HIGH",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: true,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "japanese-emoticons",
    source_name: "japanese-emoticons (roodcode)",
    source_url: "https://github.com/roodcode/japanese-emoticons",
    repository_url: "https://github.com/roodcode/japanese-emoticons",
    source_type: "github",
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "UNKNOWN",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "FAILED",
    quality_status: "UNKNOWN",
    notes: ["Repository 404 at audit time"],
    enabled_for_collection: false,
    enabled_for_publication: false,
    phase5_status: "INACCESSIBLE",
  },
  {
    source_id: "kaomoji-vaneenige",
    source_name: "kaomoji (vaneenige)",
    source_url: "https://www.npmjs.com/package/kaomoji",
    repository_url: "https://github.com/vaneenige/kaomoji",
    source_type: "npm",
    data_type: "kaomoji",
    collection_method: "npm_package",
    license_status: "UNKNOWN",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "FAILED",
    quality_status: "UNKNOWN",
    notes: ["GitHub repo 404; npm fallback attempted"],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "REVIEW_REQUIRED",
  },
  {
    source_id: "emoticon-wooorm",
    source_name: "emoticon (wooorm)",
    source_url: "https://github.com/wooorm/emoticon",
    ...gh("wooorm", "emoticon"),
    data_type: "emoticon",
    collection_method: "github_raw",
    license_status: "APPROVED",
    license_name: "MIT",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://github.com/wooorm/emoticon/blob/main/license",
    license_url: "https://github.com/wooorm/emoticon/blob/main/license",
    verification_date: "2026-08-19",
    verification_status: "VERIFIED",
    quality_status: "HIGH",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: true,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "generate-kaomoji",
    source_name: "generate-kaomoji",
    source_url: "https://github.com/xav-ie/generate-kaomoji",
    ...gh("xav-ie", "generate-kaomoji"),
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "PARTIALLY_VERIFIED",
    quality_status: "MEDIUM",
    notes: ["Static kaomoji.json dataset; generator templates not expanded"],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "kawaii-faces",
    source_name: "kawaii-faces",
    source_url: "https://github.com/matthewsimo/kawaii-faces",
    ...gh("matthewsimo", "kawaii-faces"),
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "APPROVED",
    license_name: "MIT",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://github.com/matthewsimo/kawaii-faces/blob/master/LICENSE",
    license_url: "https://github.com/matthewsimo/kawaii-faces/blob/master/LICENSE",
    verification_date: "2026-08-19",
    verification_status: "VERIFIED",
    quality_status: "HIGH",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: true,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "kaomoji-caption",
    source_name: "kaomoji_caption (HuggingFace)",
    source_url: "https://huggingface.co/datasets/mrzjy/kaomoji_caption",
    repository_url: "https://huggingface.co/datasets/mrzjy/kaomoji_caption",
    source_type: "huggingface",
    data_type: "kaomoji",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: "https://huggingface.co/datasets/mrzjy/kaomoji_caption",
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "PARTIALLY_VERIFIED",
    quality_status: "MEDIUM",
    notes: ["Captions preserved as metadata only"],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "node-kaomoji",
    source_name: "node-kaomoji",
    source_url: "https://github.com/omnidan/node-kaomoji",
    ...gh("omnidan", "node-kaomoji"),
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "APPROVED",
    license_name: "MIT",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://github.com/omnidan/node-kaomoji/blob/master/LICENSE",
    license_url: "https://github.com/omnidan/node-kaomoji/blob/master/LICENSE",
    verification_date: "2026-08-19",
    verification_status: "VERIFIED",
    quality_status: "HIGH",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: true,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "kaomoji-json",
    source_name: "kaomoji-json",
    source_url: "https://github.com/chengxuncc/kaomoji-json",
    repository_url: "https://github.com/chengxuncc/kaomoji-json",
    source_type: "github",
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "UNKNOWN",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "FAILED",
    quality_status: "UNKNOWN",
    notes: ["Primary repo 404; fallback github.com/6/kaomoji-json attempted"],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "REVIEW_REQUIRED",
  },
  {
    source_id: "random-kaomoji",
    source_name: "random-kaomoji",
    source_url: "https://github.com/6/random-kaomoji",
    ...gh("6", "random-kaomoji"),
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "PARTIALLY_VERIFIED",
    quality_status: "MEDIUM",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "ACTIVE_RELEVANT",
  },
  {
    source_id: "japaneseemoticons-org",
    source_name: "JapaneseEmoticons.org",
    source_url: "https://japaneseemoticons.org",
    repository_url: null,
    source_type: "website",
    data_type: "kaomoji",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-08-19",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [],
    enabled_for_collection: true,
    enabled_for_publication: false,
    phase5_status: "ACTIVE_RELEVANT",
  },
] as const;

export function getPhase5SourceById(sourceId: string): Phase5SourceDefinition | undefined {
  return PHASE5_SOURCE_REGISTRY.find((s) => s.source_id === sourceId);
}

export function getPhase5UniqueSourceCount(): number {
  return PHASE5_SOURCE_REGISTRY.length;
}

export function listPhase5CollectionSources(): Phase5SourceDefinition[] {
  return PHASE5_SOURCE_REGISTRY.filter((s) => s.enabled_for_collection);
}
