import type { SourceRecord } from "../types";

/** Single source of truth for all Kaomoji candidate sources. */
export const KAOMOJI_SOURCE_REGISTRY: readonly SourceRecord[] = [
  {
    source_id: "emoticon-data",
    source_name: "emoticon-data (w33ble)",
    source_url: "https://github.com/w33ble/emoticon-data",
    data_type: "emoticon",
    collection_method: "github_raw",
    license_status: "APPROVED",
    license_name: "MIT",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://github.com/w33ble/emoticon-data/blob/master/LICENSE",
    license_url: "https://github.com/w33ble/emoticon-data/blob/master/LICENSE",
    verification_date: "2026-03-20",
    verification_status: "VERIFIED",
    quality_status: "HIGH",
    notes: [
      "MIT-licensed JSON dataset on GitHub/npm.",
      "Accessible != redistributable without license; MIT explicitly permits redistribution.",
    ],
    enabled_for_collection: true,
    enabled_for_publication: true,
  },
  {
    source_id: "kaomoji-tagged",
    source_name: "kaomoji-data (kaomojikan)",
    source_url: "https://github.com/kaomojikan/kaomoji-data",
    data_type: "kaomoji",
    collection_method: "github_raw",
    license_status: "APPROVED",
    license_name: "MIT",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://github.com/kaomojikan/kaomoji-data/blob/main/LICENSE",
    license_url: "https://github.com/kaomojikan/kaomoji-data/blob/main/LICENSE",
    verification_date: "2026-03-20",
    verification_status: "VERIFIED",
    quality_status: "HIGH",
    notes: [
      "Tagged/categorized MIT kaomoji dataset (~1,700 entries).",
      "Kaomoji characters are Unicode sequences; curation metadata is MIT.",
    ],
    enabled_for_collection: true,
    enabled_for_publication: true,
  },
  {
    source_id: "wikipedia",
    source_name: "Wikipedia — List of emoticons",
    source_url: "https://en.wikipedia.org/wiki/List_of_emoticons",
    data_type: "mixed",
    collection_method: "wikimedia_api",
    license_status: "ATTRIBUTION_REQUIRED",
    license_name: "CC BY-SA 3.0",
    commercial_use: true,
    redistribution: true,
    modification: true,
    attribution_required: true,
    terms_url: "https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0/",
    verification_date: "2026-03-20",
    verification_status: "PARTIALLY_VERIFIED",
    quality_status: "MEDIUM",
    notes: [
      "Wikimedia content requires attribution and ShareAlike compliance for derivatives.",
      "Collection via Wikimedia API only; no HTML scraping.",
    ],
    enabled_for_collection: true,
    enabled_for_publication: true,
  },
  {
    source_id: "toolcalculator",
    source_name: "ToolCalculator emoticons",
    source_url: "https://www.toolcalculator.com",
    data_type: "emoticon",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-03-20",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [
      "Website terms not verified for commercial redistribution.",
      "Manual import pathway only until license is confirmed.",
    ],
    enabled_for_collection: false,
    enabled_for_publication: false,
  },
  {
    source_id: "kaomojis-org",
    source_name: "kaomojis.org",
    source_url: "https://kaomojis.org",
    data_type: "kaomoji",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-03-20",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [
      "Publicly accessible site; redistribution rights not verified.",
      "Manual import via data/kaomoji/imports/kaomojis-org.json when permitted.",
    ],
    enabled_for_collection: false,
    enabled_for_publication: false,
  },
  {
    source_id: "messletters",
    source_name: "Messletters emoticons",
    source_url: "https://www.messletters.com",
    data_type: "emoticon",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-03-20",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [
      "Third-party reports indicate site availability issues.",
      "No verified license for automated collection or redistribution.",
    ],
    enabled_for_collection: false,
    enabled_for_publication: false,
  },
  {
    source_id: "textemoticons",
    source_name: "TextEmoticons",
    source_url: "https://textemoticons.com",
    data_type: "emoticon",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-03-20",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [
      "Site reported broken/unavailable in community datasets.",
      "Manual import only if rights are confirmed.",
    ],
    enabled_for_collection: false,
    enabled_for_publication: false,
  },
  {
    source_id: "emoticonstext",
    source_name: "EmoticonsText",
    source_url: "https://emoticonstext.com",
    data_type: "emoticon",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-03-20",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [
      "Public website; commercial reuse not verified.",
      "Documented manual import pathway.",
    ],
    enabled_for_collection: false,
    enabled_for_publication: false,
  },
  {
    source_id: "slangit",
    source_name: "SlangIt emoticons",
    source_url: "https://slangit.com/emoticons",
    data_type: "emoticon",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: "https://slangit.com/terms.php",
    license_url: null,
    verification_date: "2026-03-20",
    verification_status: "UNVERIFIED",
    quality_status: "UNKNOWN",
    notes: [
      "Terms page exists but content redistribution rights not confirmed.",
      "Manual import only.",
    ],
    enabled_for_collection: false,
    enabled_for_publication: false,
  },
  {
    source_id: "fastemoji",
    source_name: "FastEmoji",
    source_url: "https://fastemoji.com",
    data_type: "mixed",
    collection_method: "documented_import",
    license_status: "REVIEW_REQUIRED",
    license_name: null,
    commercial_use: null,
    redistribution: null,
    modification: null,
    attribution_required: false,
    terms_url: null,
    license_url: null,
    verification_date: "2026-03-20",
    verification_status: "UNVERIFIED",
    quality_status: "LOW",
    notes: [
      "Community reports of low-quality AI-generated listings.",
      "No verified license; manual import only if rights confirmed.",
    ],
    enabled_for_collection: false,
    enabled_for_publication: false,
  },
] as const;

export function getSourceById(sourceId: string): SourceRecord | undefined {
  return KAOMOJI_SOURCE_REGISTRY.find((s) => s.source_id === sourceId);
}

export function listCollectionEnabledSources(): SourceRecord[] {
  return KAOMOJI_SOURCE_REGISTRY.filter((s) => s.enabled_for_collection);
}

export function listPublicationEnabledSources(): SourceRecord[] {
  return KAOMOJI_SOURCE_REGISTRY.filter((s) => s.enabled_for_publication);
}
